### ISSUE TITLE
Following exceptions happened soon after this one, most probably they are induced.

### ISSUE THREAD

**Issue by hualei1234567** [nmeylan/power-mode-3-intellij-plugin#2]
java.nio.file.FileSystemNotFoundException
	at com.sun.nio.zipfs.ZipFileSystemProvider.getFileSystem(ZipFileSystemProvider.java:171)
	at com.sun.nio.zipfs.ZipFileSystemProvider.getPath(ZipFileSystemProvider.java:157)
	at java.nio.file.Paths.get(Paths.java:143)
	at com.nmeylan.powermode.util.ImageUtil.imagesForPath(ImageUtil.java:44)
	at com.nmeylan.powermode.element.PowerFlame.findFlameImages(PowerFlame.java:58)
	at com.nmeylan.powermode.element.PowerFlame.<init>(PowerFlame.java:47)
	at com.nmeylan.powermode.management.ElementOfPowerContainer.addFlames(ElementOfPowerContainer.java:143)
	at com.nmeylan.powermode.management.ElementOfPowerContainer.initializeAnimation(ElementOfPowerContainer.java:92)
	at com.nmeylan.powermode.management.ElementOfPowerContainerManager.initializeInUI(ElementOfPowerContainerManager.java:69)
	at com.nmeylan.powermode.management.ElementOfPowerContainerManager.lambda$initializeAnimation$1(ElementOfPowerContainerManager.java:64)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:781)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:722)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by PhysicalElective2** [comment]
I developed the sonarlint plug-in for the second time and encountered this problem after packaging and installing

**Comment by simonmittag** [comment]
I am also receiving this 100s of times during normal operation. it doesn't seem to affect functionality but it does clutter the IDEA error log. Can this simply be wrapped in a catch?

java.nio.file.FileSystemNotFoundException
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.getFileSystem(ZipFileSystemProvider.java:169)
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.getPath(ZipFileSystemProvider.java:155)
	at java.base/java.nio.file.Path.of(Path.java:208)
	at java.base/java.nio.file.Paths.get(Paths.java:97)
	at com.nmeylan.powermode.util.ImageUtil.imagesForPath(ImageUtil.java:44)
	at com.nmeylan.powermode.element.PowerFlame.findFlameImages(PowerFlame.java:58)
	at com.nmeylan.powermode.element.PowerFlame.<init>(PowerFlame.java:47)
	at com.nmeylan.powermode.management.ElementOfPowerContainer.addFlames(ElementOfPowerContainer.java:143)
	at com.nmeylan.powermode.management.ElementOfPowerContainer.initializeAnimation(ElementOfPowerContainer.java:92)
	at com.nmeylan.powermode.management.ElementOfPowerContainerManager.initializeInUI(ElementOfPowerContainerManager.java:69)
	at com.nmeylan.powermode.management.ElementOfPowerContainerManager.lambda$initializeAnimation$1(ElementOfPowerContainerManager.java:64)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:976)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:843)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:454)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:773)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:453)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:822)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:507)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
